### ISSUE TITLE
Gestures problem

### ISSUE THREAD

**Issue by batman1208** [hanleyweng/Gesture-Recognition-101-CoreML-ARKit#1]
Hello, do you have only two gestures for this DEMO?

**Comment by hanleyweng** [comment]
That is correct. 

The purpose of this demo is so it can be used as an example to train your own examples by following [this tutorial](https://medium.com/@hunter.ley.ward/create-your-own-object-recognizer-ml-on-ios-7f8c09b461a1). For example, you could train your own classifier with multiple gestures.
